//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Driver_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> License_ID { get; set; }
        public Nullable<int> Transport_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Phone { get; set; }
        public string Driver_License { get; set; }
    
        public virtual LicenseType LicenseType { get; set; }
        public virtual Order Order { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual Transport Transport1 { get; set; }
    }
}
