//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicenseType()
        {
            this.Drivers = new HashSet<Driver>();
        }
    
        public int License_ID { get; set; }
        public bool License_A1 { get; set; }
        public bool License_A2 { get; set; }
        public bool License_B1 { get; set; }
        public bool License_B2 { get; set; }
        public bool License_E { get; set; }
        public bool License_F { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
